source 'https://rubygems.org'

gem 'dashing'
gem 'activesupport'
gem 'dotenv'
gem 'httparty'
gem 'codeship'
gem 'uptimerobot'
gem 'aws-sdk'
gem 'nokogiri'
gem 'google-api-client'
gem 'pry'
gem 'rest-client'
gem 'google_drive'